### ISSUE TITLE
Custom chip widget 생성하기

### ISSUE THREAD

**Issue by ChiwanAhn** [ChiwanAhn/winterview#1]
**Expected result**
![image](https://user-images.githubusercontent.com/25087511/89087915-e545c780-d363-11ea-8946-21ab991e2e3d.png)

https://www.figma.com/file/S1YKKKpfj8NMCRJskTLGOG/winterview?node-id=0%3A1

**What to do**
1. 커스텀 칩 컴포넌트를 생성합니다
2. color, child 를 인자로 받아야합니다
3. border color는 글자의 색과 동일해야합니다

사용 예시
```
CustomChip(color: Colors.blue, child: Text('어려운 질문'));
```

위젯 안에 기본 텍스트 색상을 border컬러로 지정해주는 부분 필요합니다
기본색상은 RGB(85,85,85) 지정하셔도 좋습니다
완료된 결과물의 캡쳐를 올려주세요

인터뷰 카드 컴포넌트에는 적용하지 않으셔도 좋습니다

**Comment by kcy0142** [comment]
interview_card  
QuestionTypeChip(color: color1, child: Text(interview.questionType)),

`class QuestionTypeChip extends StatelessWidget {

  final Color color;
  final Widget child;
  QuestionTypeChip({@required this.color,@required this.child});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(
          color: color ,
          width: 1,
        ),
        borderRadius: BorderRadius.circular(8),
      ),
      padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      child: DefaultTextStyle(
        style: TextStyle(
          color: color,
          fontWeight: FontWeight.bold,
          fontSize: 13,
        ),
        child: child,
      ),
    );
  }

}
`
![mission1](https://user-images.githubusercontent.com/1396463/89101840-be0ff880-d43e-11ea-8063-8bb6f93e8994.PNG)
